package Telas;

public class FormGerenciaAdm extends javax.swing.JFrame {

    /**
     * Creates new form FormGerenciaAdm
     */
    public FormGerenciaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGerenciar = new javax.swing.JMenu();
        menuGerenciarAutor = new javax.swing.JMenuItem();
        menuGerenciarCategorias = new javax.swing.JMenuItem();
        menuGerenciarEmprestimo = new javax.swing.JMenuItem();
        menuGerenciarFuncionario = new javax.swing.JMenuItem();
        menuGerenciarLivro = new javax.swing.JMenuItem();
        menuGerenciarUsuario = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        menuGerenciar.setText("Gerenciar");

        menuGerenciarAutor.setText("Autor");
        menuGerenciarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarAutorActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarAutor);

        menuGerenciarCategorias.setText("Categorias");
        menuGerenciarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarCategoriasActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarCategorias);

        menuGerenciarEmprestimo.setText("Empréstimo");
        menuGerenciarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarEmprestimoActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarEmprestimo);

        menuGerenciarFuncionario.setText("Funcionário");
        menuGerenciarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarFuncionarioActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarFuncionario);

        menuGerenciarLivro.setText("Livro");
        menuGerenciarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarLivroActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarLivro);

        menuGerenciarUsuario.setText("Usuário");
        menuGerenciarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarUsuarioActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerenciarUsuario);

        jMenuBar1.add(menuGerenciar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGerenciarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarFuncionarioActionPerformed
       
        FormFuncionario form = new FormFuncionario();
        
        form.setTitle("Funcionário");
        //form.setLocationRelativeTo(this);
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_menuGerenciarFuncionarioActionPerformed

    private void menuGerenciarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarAutorActionPerformed
        
        FormAutor form = new FormAutor();
        
        form.setTitle("Autor");
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_menuGerenciarAutorActionPerformed

    private void menuGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarCategoriasActionPerformed
        
        FormCategorias form = new FormCategorias();
        
        form.setTitle("Categoria");
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true);
    }//GEN-LAST:event_menuGerenciarCategoriasActionPerformed

    private void menuGerenciarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarLivroActionPerformed
        
        FormLivro form = new FormLivro();
        
        form.setTitle("Livro");
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_menuGerenciarLivroActionPerformed

    private void menuGerenciarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarUsuarioActionPerformed
        
        FormUsuario form = new FormUsuario();

        form.setTitle("Usuário");
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_menuGerenciarUsuarioActionPerformed

    private void menuGerenciarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarEmprestimoActionPerformed
        
        FormEmprestimo form = new FormEmprestimo(1);
        
        form.setTitle("Empréstimo");
        form.setLocationRelativeTo(null);// no centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); // mostra a janela
    }//GEN-LAST:event_menuGerenciarEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormGerenciaAdm tela;
                tela = new FormGerenciaAdm();    
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenuItem menuGerenciarAutor;
    private javax.swing.JMenuItem menuGerenciarCategorias;
    private javax.swing.JMenuItem menuGerenciarEmprestimo;
    private javax.swing.JMenuItem menuGerenciarFuncionario;
    private javax.swing.JMenuItem menuGerenciarLivro;
    private javax.swing.JMenuItem menuGerenciarUsuario;
    // End of variables declaration//GEN-END:variables
}
